// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeEVLK-JPqGA6Nxb8MmEnZ21L0flJw8CE',
    appId: '1:980322801318:web:de7341532824415f364667',
    messagingSenderId: '980322801318',
    projectId: 'myproject-3f4a1',
    authDomain: 'myproject-3f4a1.firebaseapp.com',
    storageBucket: 'myproject-3f4a1.firebasestorage.app',
    measurementId: 'G-5066XJ9VR6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXRDWYIvUZ3cKFe7-b6GHRngGFiJv6PM8',
    appId: '1:980322801318:android:77a889513638e179364667',
    messagingSenderId: '980322801318',
    projectId: 'myproject-3f4a1',
    storageBucket: 'myproject-3f4a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJGy-_Xk6uEsAEgB3XlwcelMb8my75S_E',
    appId: '1:980322801318:ios:8f52a5794827d4ca364667',
    messagingSenderId: '980322801318',
    projectId: 'myproject-3f4a1',
    storageBucket: 'myproject-3f4a1.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJGy-_Xk6uEsAEgB3XlwcelMb8my75S_E',
    appId: '1:980322801318:ios:8f52a5794827d4ca364667',
    messagingSenderId: '980322801318',
    projectId: 'myproject-3f4a1',
    storageBucket: 'myproject-3f4a1.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeEVLK-JPqGA6Nxb8MmEnZ21L0flJw8CE',
    appId: '1:980322801318:web:aecb717dd0061eaf364667',
    messagingSenderId: '980322801318',
    projectId: 'myproject-3f4a1',
    authDomain: 'myproject-3f4a1.firebaseapp.com',
    storageBucket: 'myproject-3f4a1.firebasestorage.app',
    measurementId: 'G-1TN3YM9BF6',
  );

}